Repository Sam071100/CodeForces-Solutions, pull requests merged in 2021-10, with the labels that each got.

#4 Chess Tournament
  Chess_Tournament
Labels: hacktoberest-accepted

#3 basic algorithms
  dfs
Labels: hacktoberest-accepted

#2 Codeforces Round #723 (Div. 2), problem: (A) Mean Inequality
  mean_inequality.cpp
Labels: hacktoberest-accepted

#6 CodeChef Problem: BININVER
  odd_gcd.cpp
Labels: hacktoberest-accepted

#7 Added CodeChef solution for problem numberMirror
  number_mirror.cpp
Labels: hacktoberest-accepted, hacktoberfest

#8 Codeforces Round #735 (Div. 2), problem: (A) Cherry
  .vscode/settings.json
  a_cherry.cpp
  diwali1.cpp
Labels: hacktoberest-accepted

#9 Create balloon burst problem
  Shortest path to reach one prime to other by changing single digit at a time
  balloon burst problem
Labels: hacktoberest-accepted

#10 Implement AVL Tree
  Heapsort
  Implement AVL Tree
Labels: hacktoberest-accepted

#11 Added codechef EITA problem solution.
  EITA.cpp
Labels: hacktobefest2021, hacktoberfest-accepted

#12 Create Graph island
  Graph island
Labels: hacktoberfest-accepted

#13 Added CodeChef solution for Flow001
  CodeChef_FLOW001.cpp
Labels: hacktoberfest-accepted

#17 118A String task
  String_task.cpp
Labels: hacktoberfest-accepted

#16 Added solution for CodeChef problem First and Last Digit
  FirstAndLastDigit.cpp
Labels: hacktoberfest-accepted

#15 Added Solution for ATM problem on Codechef
  ATM_Codechef.cpp
Labels: hacktoberfest-accepted

#14 Add files via upload
  Chess Format.cpp
Labels: hacktoberfest-accepted
